#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MacOSX-File
version:      0.68
version_from: File.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
